### ISSUE TITLE
PaperPlatform#getEntityPosition fails when not in the main thread

### ISSUE THREAD

**Issue by DaddyRobLIVE** [naturecodevoid/voicechat-discord#56]
**Describe the bug**
Can't capture entity for voicechat due to Async processing

**To Reproduce**
1. Install SparklyPaper - https://github.com/SparklyPower/SparklyPaper
2. Install Simple Voicechat and DVC
3. Do all the steps necessary
4. Try to talk with someone
5. See error - https://mclo.gs/ZpL6iBt

**Expected behavior**
I should be able to communicate without any issues but simple voice chat users can hear me but I can't hear them.

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/109517972/4f130fd9-092a-4fe7-8786-8e96a2e5f527)

**Logs**
I don't think this is necessary but let me know if you really need it.

**Versions (please complete the following information):**
- Minecraft: 
- Loader: SparklyPaper - https://github.com/SparklyPower/SparklyPaper
- Simple Voice Chat: voicechat 2.5.15
- Simple Voice Chat Discord Bridge:  voicechat-discord 3.0.0

**Additional context**
None

**Comment by DaddyRobLIVE** [comment]
I did more tests, I tried doing it with normal paper mc and it still has the error. One thing we did is I made a group and I joined there and we can both hear each other.

**Comment by naturecodevoid** [comment]
This used to be an issue a while ago, looks like it's back. Not sure when I will be able to work on a fix. What Minecraft version?

**Comment by naturecodevoid** [comment]
@DaddyRobLIVE Can you try using the nightly build at https://github.com/naturecodevoid/voicechat-discord/actions/runs/9817676120? Jars will be at the bottom

**Comment by DaddyRobLIVE** [comment]
Sure. I'll check this out.

**Comment by DaddyRobLIVE** [comment]
![image](https://github.com/naturecodevoid/voicechat-discord/assets/109517972/198948a5-7664-4837-a082-dabc7cbfb01b)
Not yet fixed :/

**Comment by DaddyRobLIVE** [comment]
![image](https://github.com/naturecodevoid/voicechat-discord/assets/109517972/66c5dec6-71a6-4041-a655-0833f9cf57f7)

**Comment by DaddyRobLIVE** [comment]
> This used to be an issue a while ago, looks like it's back. Not sure when I will be able to work on a fix. What Minecraft version?

The server is using Minecraft 1.20.6 SparklyPaper
I tried using the voice chat on Bedrock for Windows 1.21+

**Comment by naturecodevoid** [comment]
I will not be making any effort to support offline mode. The fix should've worked in 1.21 but since you're using 1.20.6, it didn't work. I will look into this further after confirming that it is a legitimate issue.

**Comment by DaddyRobLIVE** [comment]
Sure no problem with offline players. Just please try to fix it for version 1.20.6 thank you so much!

**Comment by DaddyRobLIVE** [comment]
By the way, do you have a discord so that I can contact you privately? I have some proposal that might interest you.

**Comment by naturecodevoid** [comment]
My discord is on my GitHub profile - it's just @naturecodevoid

**Comment by DaddyRobLIVE** [comment]
Done, I've added you.

**Comment by naturecodevoid** [comment]
This nightly build should fix it. https://github.com/naturecodevoid/voicechat-discord/actions/runs/9829671893

**Comment by DaddyRobLIVE** [comment]
I'll check it again, thanks for you hardwork.

**Comment by DaddyRobLIVE** [comment]
Confirmed fixed!

**Comment by BenGuined** [comment]
I still have that error come up even with the 1.21 build you posted. I can hear people using the discord bridge but they cannot hear me. any clue what is wrong
[18:51:34 ERROR]: [voicechat] Voice chat server error
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2582) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:2088) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at voicechat-discord-paper-3.0.0.jar/dev.naturecodevoid.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:45) ~[voicechat-discord-paper-3.0.0.jar:?]
        at voicechat-discord-paper-3.0.0.jar/dev.naturecodevoid.voicechatdiscord.DiscordBot.handlePacket(DiscordBot.java:285) ~[voicechat-discord-paper-3.0.0.jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:383) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:431) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[voicechat-bukkit-2.5.16 (1).jar:?]
[18:51:34 ERROR]: Thread VoiceChatPacketProcessingThread failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2582) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:2088) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at voicechat-discord-paper-3.0.0.jar/dev.naturecodevoid.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:45) ~[voicechat-discord-paper-3.0.0.jar:?]
        at voicechat-discord-paper-3.0.0.jar/dev.naturecodevoid.voicechatdiscord.DiscordBot.handlePacket(DiscordBot.java:285) ~[voicechat-discord-paper-3.0.0.jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:383) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:431) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303) ~[voicechat-bukkit-2.5.16 (1).jar:?]
        at voicechat-bukkit-2.5.16 (1).jar/de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[voicechat-bukkit-2.5.16 (1).jar:?]

**Comment by naturecodevoid** [comment]
You are not using the build posted. If it still doesn't work just wait for 3.0.1
